// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= Advanced Scenarios
:toc: left
:toclevels: 3

== Fetch Index Files Locally

Let's say that you want to run several queries against the index files, and you'd like to
store the index files (e.g. `cdx-0000.gz`...) locally so that you don't have to pull
300GB for each crawl and each time you want to process the index files.

Use this link:../examples/fetch-indices-config.json[configuration file] to gather the `gz`
index files from a list of Common Crawl `cc-index.paths.gz` files.

[source,json]
----
{
  "indices": {
    "paths": [
      "crawl-data/CC-MAIN-2025-08/cc-index.paths.gz"
    ]
  },
  "docs": {
    "path": "my-indices"
  },
  "numThreads": 2
}
----

[source,bash]
----
java -jar commoncrawl-fetcher-lite-X.Y.Z.jar FetchIndices fetch-indices-config.json
----

That will put the index files (~300GB per crawl!) in the local directory `my-indices`, and
it will maintain the original paths so that the other tools may be run against this local
cache.

== Extract Selected Files from Local Indices

After downloading the index files locally, you can extract the literal files from the
WARCs using the local index files with this
link:../examples/fetch-files-from-local-indices.json[config].

[source,bash]
----
java -jar commoncrawl-fetcher-lite-X.Y.Z.jar fetch-files-from-local-indices.json
----

[source,json]
----
{
  "numThreads": 2,
  "maxRecords": 100000000,
  "maxFilesExtracted": 100,
  "maxFilesTruncated": 1000,
  "indices": {
    "basePath": "my-indices"
  },
  "indexFetcher" : {
    "basePath": "my-indices"
  },
  "docs": {
    "path": "octets"
  },
  "recordSelector": {
    "should": {
      "mime_detected": [
        { "match": "application/octet-stream", "sample": 0.8 }
      ]
    },
    "must": {
      "status": [
        { "match": "200" }
      ]
    }
  },
  "targetPathPattern": "xx/xx/xxx"
}
----

== Count Mimes from Local Indices

Config file (`count.json`):

[source,json]
----
{
  "numThreads": 10,
  "indices": {
    "basePath": "my-indices"
  },
  "indexFetcher" : {
    "basePath": "my-indices"
  },
  "recordSelector": {
    "must": {
      "status": [
        { "match": "200" }
      ]
    }
  }
}
----

[source,bash]
----
java -jar commoncrawl-fetcher-lite-X.Y.Z.jar CountMimes count.json
----
